sudo: true
language: python
matrix:
    include:
        - python: 2.7
          os: linux
          dist: precise
          env: TOXENV=py27
        - python: 2.7
          os: linux
          dist: trusty
          env: TOXENV=py27
        - python: 3.4
          os: linux
          dist: precise
          env: TOXENV=py34
        - python: 3.4
          os: linux
          dist: trusty
          env: TOXENV=py34
        - python: 3.5
          os: linux
          dist: precise
          env: TOXENV=py35
        - python: 3.5
          os: linux
          dist: trusty
          env: TOXENV=py35
        - python: 3.6
          os: linux
          dist: precise
          env: TOXENV=py36
        - python: 3.6
          os: linux
          dist: trusty
          env: TOXENV=py36
        - python: 2.7
          os: linux
          dist: precise
          env: TOXENV=pep8
        - python: 2.7
          os: linux
          dist: trusty
          env: TOXENV=pep8
        - python: 2.7
          os: linux
          dist: precise
          env: TOXENV=bandit
        - python: 2.7
          os: linux
          dist: trusty
          env: TOXENV=bandit
        - python: 2.7
          os: linux
          dist: precise
          env: TOXENV=docs
        - python: 2.7
          os: linux
          dist: trusty
          env: TOXENV=docs
install:
  # Pin six to >= 1.11.0 to avoid cherrypy/cheroot dependency errors
  # For more info, see: https://github.com/OpenKMIP/SLUGS/issues/3
  - pip uninstall -y six
  - pip install six>=1.11.0
  - pip install tox
  - pip install bandit
  - pip install codecov
  - python setup.py install
script:
  - tox
after_success:
  - codecov
