sudo: true
language: python
matrix:
    include:
        - python: 2.7
          os: linux
          dist: precise
          env: TOXENV=py27 RUN_INTEGRATION_TESTS=0
        - python: 2.7
          os: linux
          dist: trusty
          env: TOXENV=py27 RUN_INTEGRATION_TESTS=0
        - python: 2.7
          os: linux
          dist: xenial
          env: TOXENV=py27 RUN_INTEGRATION_TESTS=0
        - python: 2.7
          os: linux
          dist: precise
          env: TOXENV=py27 RUN_INTEGRATION_TESTS=1
        - python: 2.7
          os: linux
          dist: trusty
          env: TOXENV=py27 RUN_INTEGRATION_TESTS=1
        - python: 2.7
          os: linux
          dist: xenial
          env: TOXENV=py27 RUN_INTEGRATION_TESTS=1
        - python: 3.4
          os: linux
          dist: precise
          env: TOXENV=py34 RUN_INTEGRATION_TESTS=0
        - python: 3.4
          os: linux
          dist: trusty
          env: TOXENV=py34 RUN_INTEGRATION_TESTS=0
        - python: 3.4
          os: linux
          dist: xenial
          env: TOXENV=py34 RUN_INTEGRATION_TESTS=0
        - python: 3.4
          os: linux
          dist: precise
          env: TOXENV=py34 RUN_INTEGRATION_TESTS=1
        - python: 3.4
          os: linux
          dist: trusty
          env: TOXENV=py34 RUN_INTEGRATION_TESTS=1
        - python: 3.4
          os: linux
          dist: xenial
          env: TOXENV=py34 RUN_INTEGRATION_TESTS=1
        - python: 3.5
          os: linux
          dist: precise
          env: TOXENV=py35 RUN_INTEGRATION_TESTS=0
        - python: 3.5
          os: linux
          dist: trusty
          env: TOXENV=py35 RUN_INTEGRATION_TESTS=0
        - python: 3.5
          os: linux
          dist: xenial
          env: TOXENV=py35 RUN_INTEGRATION_TESTS=0
        - python: 3.5
          os: linux
          dist: precise
          env: TOXENV=py35 RUN_INTEGRATION_TESTS=1
        - python: 3.5
          os: linux
          dist: trusty
          env: TOXENV=py35 RUN_INTEGRATION_TESTS=1
        - python: 3.5
          os: linux
          dist: xenial
          env: TOXENV=py35 RUN_INTEGRATION_TESTS=1
        - python: 3.6
          os: linux
          dist: precise
          env: TOXENV=py36 RUN_INTEGRATION_TESTS=0
        - python: 3.6
          os: linux
          dist: trusty
          env: TOXENV=py36 RUN_INTEGRATION_TESTS=0
        - python: 3.6
          os: linux
          dist: xenial
          env: TOXENV=py36 RUN_INTEGRATION_TESTS=0
        - python: 3.6
          os: linux
          dist: precise
          env: TOXENV=py36 RUN_INTEGRATION_TESTS=1
        - python: 3.6
          os: linux
          dist: trusty
          env: TOXENV=py36 RUN_INTEGRATION_TESTS=1
        - python: 3.6
          os: linux
          dist: xenial
          env: TOXENV=py36 RUN_INTEGRATION_TESTS=1
        - python: 2.7
          os: linux
          dist: precise
          env: TOXENV=pep8 RUN_INTEGRATION_TESTS=0
        - python: 2.7
          os: linux
          dist: trusty
          env: TOXENV=pep8 RUN_INTEGRATION_TESTS=0
        - python: 2.7
          os: linux
          dist: xenial
          env: TOXENV=pep8 RUN_INTEGRATION_TESTS=0
        - python: 2.7
          os: linux
          dist: precise
          env: TOXENV=bandit RUN_INTEGRATION_TESTS=0
        - python: 2.7
          os: linux
          dist: trusty
          env: TOXENV=bandit RUN_INTEGRATION_TESTS=0
        - python: 2.7
          os: linux
          dist: xenial
          env: TOXENV=bandit RUN_INTEGRATION_TESTS=0
        - python: 2.7
          os: linux
          dist: precise
          env: TOXENV=docs RUN_INTEGRATION_TESTS=0
        - python: 2.7
          os: linux
          dist: trusty
          env: TOXENV=docs RUN_INTEGRATION_TESTS=0
        - python: 2.7
          os: linux
          dist: xenial
          env: TOXENV=docs RUN_INTEGRATION_TESTS=0
install:
  # Pin six to >= 1.11.0 to avoid cherrypy/cheroot dependency errors
  # For more info, see: https://github.com/OpenKMIP/SLUGS/issues/3
  - pip uninstall -y six
  - pip install six>=1.11.0
  # Install setuptools_scm via pip to avoid conflict with easy_install
  # For more info, see: https://github.com/OpenKMIP/SLUGS/issues/15
  - pip install setuptools_scm
  - pip install tox
  - pip install bandit
  - pip install codecov
  - python setup.py install
script:
  - ./.travis/run.sh
after_success:
  - codecov
